name: "Feature request"
description: "Suggest an idea to improve the portfolio system."
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: What do you want to see added?
      placeholder: I'd love if the site could...
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why this matters
      description: Explain the benefit or use-case.
